name = "OperationsResearchModels"
uuid = "8042aa49-e599-49ec-a8f7-b5b80cc82a88"
authors = ["Mehmet Hakan Satman <mhsatman@gmail.com>"]
version = "0.1.6"

[deps]
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"

[compat]
HiGHS = "1"
JuMP = "1"
julia = "1.6"
