name = "OperationsResearchModels"
uuid = "8042aa49-e599-49ec-a8f7-b5b80cc82a88"
version = "0.2.9"
authors = ["Mehmet Hakan Satman <mhsatman@gmail.com>"]

[deps]
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
HiGHS = "1.4"
Ipopt = "1.7"
JuMP = "1"
LinearAlgebra = "1"
Statistics = "1"
julia = "1.6"
